spring:
  application:
    name: notifications-service

server:
  port: 8001

eureka:
  client:
    ervice-url:
      default-zone: http://localhost:8761/eureka

email:
  config:
    host: smtp.gmail.com
    port: 587
    username: anamartynova87@gmail.com
    password: Admin123$%
    siteUrl: http://localhost:3000

jms:
  listener:
    broker-url: tcp://localhost:61616